# Micro Wars Lobby
# A tiny lobby UI for hosting and joining Micro Wars matches over Tailscale.
# Double-click MicroWarsLobby.bat to run. No installs needed (uses built-in Windows Forms).

param([switch]$SelfTest)  # -SelfTest generates scripts from every preset and exits (no window)

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()

$ErrorActionPreference = 'Stop'
$AppDir     = Split-Path -Parent $MyInvocation.MyCommand.Path
$PresetDir  = Join-Path $AppDir 'presets'
$GenDir     = Join-Path $AppDir 'generated'
$ConfigPath = Join-Path $AppDir 'lobby-config.json'
foreach ($d in @($PresetDir, $GenDir)) { if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d | Out-Null } }

# ---------------------------------------------------------------- config ----
function Find-BarDataDir {
    $candidates = @(
        (Join-Path $env:LOCALAPPDATA 'Programs\Beyond-All-Reason\data'),
        'C:\Program Files\Beyond-All-Reason\data'
    )
    foreach ($c in $candidates) { if (Test-Path (Join-Path $c 'engine')) { return $c } }
    return $null
}

function Find-SpringExe([string]$dataDir) {
    if (-not $dataDir) { return $null }
    $engineRoot = Join-Path $dataDir 'engine'
    if (-not (Test-Path $engineRoot)) { return $null }
    $exe = Get-ChildItem $engineRoot -Directory | Sort-Object Name -Descending |
        ForEach-Object { Join-Path $_.FullName 'spring.exe' } |
        Where-Object { Test-Path $_ } | Select-Object -First 1
    return $exe
}

$script:Config = [ordered]@{
    role         = 'Host'
    myName       = 'Michael'
    opponentName = 'Mark'
    hostIP       = '100.97.125.9'
    hostPort     = 8452
    dataDir      = ''
}
if (Test-Path $ConfigPath) {
    try {
        $loaded = Get-Content $ConfigPath -Raw | ConvertFrom-Json
        foreach ($k in @($script:Config.Keys)) {
            if ($null -ne $loaded.$k -and "$($loaded.$k)" -ne '') { $script:Config[$k] = $loaded.$k }
        }
    } catch { }
}
if (-not $script:Config.dataDir -or -not (Test-Path $script:Config.dataDir)) {
    $auto = Find-BarDataDir
    if ($auto) { $script:Config.dataDir = $auto }
}

function Save-Config {
    $script:Config | ConvertTo-Json | Set-Content -Path $ConfigPath -Encoding utf8
}

# --------------------------------------------------------------- presets ----
function Get-Presets {
    $list = @()
    Get-ChildItem $PresetDir -Filter '*.json' | Sort-Object Name | ForEach-Object {
        try { $list += (Get-Content $_.FullName -Raw | ConvertFrom-Json) } catch { }
    }
    return $list
}

# ---------------------------------------------------------- script maker ----
function New-HostScript {
    param($p)  # hashtable of current UI settings
    $mo = New-Object System.Text.StringBuilder
    [void]$mo.AppendLine("		micro_wars_enabled=1;")
    [void]$mo.AppendLine("		experimentallegionfaction=1;")
    if ($p.touchdown) {
        [void]$mo.AppendLine("		micro_wars_touchdown=1;")
        if ($p.attackerSlot -gt 0) { [void]$mo.AppendLine("		touchdown_attacker_slot=$($p.attackerSlot);") }
        [void]$mo.AppendLine("		touchdown_win_score=$($p.winScore);")
    }
    if ($p.wipeoutOnly) { [void]$mo.AppendLine("		micro_wars_wipeout_only=1;") }
    [void]$mo.AppendLine("		round_time=$($p.roundTimeMin);")
    for ($i = 1; $i -le 2; $i++) {
        $pl = $p.players[$i - 1]
        if ($pl.initial)      { [void]$mo.AppendLine("		reinforcement_initial_p$i=$($pl.initial);") }
        if ($pl.interval -gt 0 -and $pl.wave) {
            [void]$mo.AppendLine("		reinforcement_interval_p$i=$($pl.interval);")
            [void]$mo.AppendLine("		reinforcement_wave_p$i=$($pl.wave);")
            if ($pl.waveAlt) {
                [void]$mo.AppendLine("		reinforcement_wave_alt_p$i=$($pl.waveAlt);")
                [void]$mo.AppendLine("		reinforcement_wave_alt_every_p$i=$($pl.altEvery);")
            }
        }
    }
    [void]$mo.AppendLine("		units_per_round=$($p.unitsPerRound);")
    [void]$mo.AppendLine("		micro_wars_show_timer=1;")
    [void]$mo.Append("		micro_wars_commander_radar=1;")

    @"
// Generated by Micro Wars Lobby $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
[GAME]
{
	GameType=Beyond All Reason `$VERSION;
	Mapname=$($p.map);

	HostIP=0.0.0.0;
	HostPort=$($script:Config.hostPort);
	IsHost=1;
	MyPlayerName=$($p.hostName);
	MyPlayerNum=0;

	StartPosType=2;

	NumPlayers=2;
	NumTeams=2;
	NumAllyTeams=2;

	[MODOPTIONS]
	{
$($mo.ToString())
	}

	[PLAYER0]
	{
		Name=$($p.hostName);
		Team=0;
	}
	[PLAYER1]
	{
		Name=$($p.joinName);
		Team=1;
	}

	[TEAM0]
	{
		TeamLeader=0;
		AllyTeam=0;
		RgbColor=0.9 0.1 0.1;
		Side=Armada;
	}
	[TEAM1]
	{
		TeamLeader=1;
		AllyTeam=1;
		RgbColor=0.1 0.3 0.9;
		Side=Cortex;
	}

	[ALLYTEAM0]
	{
		NumAllies=0;
		StartRectLeft=0;
		StartRectRight=1;
		StartRectTop=0;
		StartRectBottom=0.30;
	}
	[ALLYTEAM1]
	{
		NumAllies=0;
		StartRectLeft=0;
		StartRectRight=1;
		StartRectTop=0.70;
		StartRectBottom=1;
	}
}
"@
}

function New-JoinScript {
    @"
// Generated by Micro Wars Lobby $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
[GAME]
{
	HostIP=$($script:Config.hostIP);
	HostPort=$($script:Config.hostPort);
	IsHost=0;
	MyPlayerName=$($script:Config.myName);
}
"@
}

# ------------------------------------------------------------ game launch ---
$script:GameProc = $null

function Start-Game([string]$scriptPath, [System.Windows.Forms.Label]$statusLabel) {
    $spring = Find-SpringExe $script:Config.dataDir
    if (-not $spring) {
        [System.Windows.Forms.MessageBox]::Show("Could not find spring.exe under:`n$($script:Config.dataDir)`n`nIs Beyond All Reason installed?", 'Micro Wars Lobby') | Out-Null
        return $false
    }
    Get-Process spring -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
    $script:GameProc = Start-Process -FilePath $spring `
        -ArgumentList @('--write-dir', $script:Config.dataDir, '--isolation', $scriptPath) `
        -PassThru
    $statusLabel.Text = "Game running (pid $($script:GameProc.Id)). This window stays open. You will return here when the game closes."
    return $true
}

# ------------------------------------------------------------------- form ---
$form = New-Object System.Windows.Forms.Form
$form.Text = 'Micro Wars Lobby'
$form.Size = New-Object System.Drawing.Size(820, 720)
$form.StartPosition = 'CenterScreen'
$form.FormBorderStyle = 'FixedSingle'
$form.MaximizeBox = $false

$font = New-Object System.Drawing.Font('Segoe UI', 9.5)
$form.Font = $font

# --- top bar: identity ---
$lblRole = New-Object System.Windows.Forms.Label
$lblRole.Text = 'I am:'
$lblRole.Location = New-Object System.Drawing.Point(15, 15)
$lblRole.AutoSize = $true

$cmbRole = New-Object System.Windows.Forms.ComboBox
$cmbRole.DropDownStyle = 'DropDownList'
[void]$cmbRole.Items.AddRange(@('Host', 'Joiner'))
$cmbRole.Location = New-Object System.Drawing.Point(60, 12)
$cmbRole.Width = 90
$cmbRole.SelectedItem = $(if ($script:Config.role -eq 'Joiner') { 'Joiner' } else { 'Host' })

$lblMyName = New-Object System.Windows.Forms.Label
$lblMyName.Text = 'My name:'
$lblMyName.Location = New-Object System.Drawing.Point(170, 15)
$lblMyName.AutoSize = $true

$txtMyName = New-Object System.Windows.Forms.TextBox
$txtMyName.Location = New-Object System.Drawing.Point(240, 12)
$txtMyName.Width = 110
$txtMyName.Text = $script:Config.myName

$lblOppName = New-Object System.Windows.Forms.Label
$lblOppName.Text = 'Opponent:'
$lblOppName.Location = New-Object System.Drawing.Point(370, 15)
$lblOppName.AutoSize = $true

$txtOppName = New-Object System.Windows.Forms.TextBox
$txtOppName.Location = New-Object System.Drawing.Point(445, 12)
$txtOppName.Width = 110
$txtOppName.Text = $script:Config.opponentName

$btnUnitNames = New-Object System.Windows.Forms.Button
$btnUnitNames.Text = 'Unit names'
$btnUnitNames.Location = New-Object System.Drawing.Point(680, 10)
$btnUnitNames.Width = 105
$btnUnitNames.Add_Click({
    $msg = @'
Common unit codenames (write lists as "name count, name count"):

armpw 10            Pawn (light raider bot)
armrock 5           Rocketeer (rocket bot)
armham 5            Hammer / Mace (plasma bot)
armwar 3            Centurion (armored assault bot)
armvang 1           Vanguard (heavy plasma mech)
armaser 5           Smuggler (radar jammer bot)
armjeth 5           Crossbow (T1 anti-air bot)
armyork 1           Shredder (T2 anti-air vehicle)
cormort 2           Sheldon (mortar bot)
corak 10            Grunt (Cortex raider bot)
corvroc 2           Negotiator (rocket truck)
corcrash 5          Trasher (Cortex T1 AA bot)
legsrail 10         Arquebus (railgun spider)
legphoenix 2        Phoenix (Legion bomber)
legeallterrainmech 1  Myrmidon (all-terrain mech)
leginc 2            Incinerator (flame mech)
leghrk 2            Thanatos (rocket mech)

Legion units work because the lobby always enables the Legion faction.
Unknown names are skipped with a warning in-game, never a crash.
'@
    [System.Windows.Forms.MessageBox]::Show($msg, 'Unit codenames') | Out-Null
})

# --- tabs ---
$tabs = New-Object System.Windows.Forms.TabControl
$tabs.Location = New-Object System.Drawing.Point(10, 45)
$tabs.Size = New-Object System.Drawing.Size(790, 580)

$tabHost = New-Object System.Windows.Forms.TabPage
$tabHost.Text = 'Host a Match'
$tabJoin = New-Object System.Windows.Forms.TabPage
$tabJoin.Text = 'Join a Match'
[void]$tabs.TabPages.Add($tabHost)
[void]$tabs.TabPages.Add($tabJoin)

# --- status bar ---
$lblStatus = New-Object System.Windows.Forms.Label
$lblStatus.Location = New-Object System.Drawing.Point(15, 635)
$lblStatus.Size = New-Object System.Drawing.Size(780, 40)
$lblStatus.Text = "Ready. BAR data: $($script:Config.dataDir)"

# ======================================================== HOST TAB ==========
$y = 12

$lblPreset = New-Object System.Windows.Forms.Label
$lblPreset.Text = 'Preset:'
$lblPreset.Location = New-Object System.Drawing.Point(12, ($y + 3))
$lblPreset.AutoSize = $true

$cmbPreset = New-Object System.Windows.Forms.ComboBox
$cmbPreset.DropDownStyle = 'DropDownList'
$cmbPreset.Location = New-Object System.Drawing.Point(70, $y)
$cmbPreset.Width = 330

$btnSavePreset = New-Object System.Windows.Forms.Button
$btnSavePreset.Text = 'Save as preset...'
$btnSavePreset.Location = New-Object System.Drawing.Point(415, ($y - 1))
$btnSavePreset.Width = 130

$btnDeletePreset = New-Object System.Windows.Forms.Button
$btnDeletePreset.Text = 'Delete preset'
$btnDeletePreset.Location = New-Object System.Drawing.Point(555, ($y - 1))
$btnDeletePreset.Width = 110

$lblPresetDesc = New-Object System.Windows.Forms.Label
$lblPresetDesc.Location = New-Object System.Drawing.Point(70, ($y + 30))
$lblPresetDesc.Size = New-Object System.Drawing.Size(690, 34)
$lblPresetDesc.ForeColor = [System.Drawing.Color]::DimGray

$y += 70

# --- match settings ---
$grpMatch = New-Object System.Windows.Forms.GroupBox
$grpMatch.Text = 'Match settings'
$grpMatch.Location = New-Object System.Drawing.Point(12, $y)
$grpMatch.Size = New-Object System.Drawing.Size(755, 115)

$lblMap = New-Object System.Windows.Forms.Label
$lblMap.Text = 'Map:'
$lblMap.Location = New-Object System.Drawing.Point(12, 27)
$lblMap.AutoSize = $true
$txtMap = New-Object System.Windows.Forms.TextBox
$txtMap.Location = New-Object System.Drawing.Point(55, 24)
$txtMap.Width = 250
$txtMap.Text = 'Quicksilver Remake 1.24'

$lblTime = New-Object System.Windows.Forms.Label
$lblTime.Text = 'Time limit (min):'
$lblTime.Location = New-Object System.Drawing.Point(330, 27)
$lblTime.AutoSize = $true
$numTime = New-Object System.Windows.Forms.NumericUpDown
$numTime.Location = New-Object System.Drawing.Point(435, 24)
$numTime.Width = 60
$numTime.Minimum = 0; $numTime.Maximum = 180; $numTime.Value = 20

$lblMult = New-Object System.Windows.Forms.Label
$lblMult.Text = 'Unit multiplier:'
$lblMult.Location = New-Object System.Drawing.Point(520, 27)
$lblMult.AutoSize = $true
$numMult = New-Object System.Windows.Forms.NumericUpDown
$numMult.Location = New-Object System.Drawing.Point(620, 24)
$numMult.Width = 60
$numMult.Minimum = 1; $numMult.Maximum = 20; $numMult.Value = 1

$chkTouchdown = New-Object System.Windows.Forms.CheckBox
$chkTouchdown.Text = 'Touchdown mode (score by holding the enemy start zone)'
$chkTouchdown.Location = New-Object System.Drawing.Point(12, 55)
$chkTouchdown.AutoSize = $true
$chkTouchdown.Checked = $true

$chkWipeout = New-Object System.Windows.Forms.CheckBox
$chkWipeout.Text = 'Wipeout only (round mode)'
$chkWipeout.Location = New-Object System.Drawing.Point(420, 55)
$chkWipeout.AutoSize = $true

$lblScore = New-Object System.Windows.Forms.Label
$lblScore.Text = 'Points to win:'
$lblScore.Location = New-Object System.Drawing.Point(12, 85)
$lblScore.AutoSize = $true
$numScore = New-Object System.Windows.Forms.NumericUpDown
$numScore.Location = New-Object System.Drawing.Point(105, 82)
$numScore.Width = 80
$numScore.Minimum = 100; $numScore.Maximum = 1000000; $numScore.Increment = 1000; $numScore.Value = 40000

$lblAttacker = New-Object System.Windows.Forms.Label
$lblAttacker.Text = 'Attacker:'
$lblAttacker.Location = New-Object System.Drawing.Point(220, 85)
$lblAttacker.AutoSize = $true
$cmbAttacker = New-Object System.Windows.Forms.ComboBox
$cmbAttacker.DropDownStyle = 'DropDownList'
[void]$cmbAttacker.Items.AddRange(@('Both score (tug of war)', 'Player 1 attacks', 'Player 2 attacks'))
$cmbAttacker.Location = New-Object System.Drawing.Point(285, 82)
$cmbAttacker.Width = 180
$cmbAttacker.SelectedIndex = 2

$grpMatch.Controls.AddRange(@($lblMap, $txtMap, $lblTime, $numTime, $lblMult, $numMult, $chkTouchdown, $chkWipeout, $lblScore, $numScore, $lblAttacker, $cmbAttacker))
$y += 125

# --- per-player army boxes ---
function New-PlayerBox([string]$title, [int]$px, [int]$py) {
    $g = New-Object System.Windows.Forms.GroupBox
    $g.Text = $title
    $g.Location = New-Object System.Drawing.Point($px, $py)
    $g.Size = New-Object System.Drawing.Size(755, 128)

    $l1 = New-Object System.Windows.Forms.Label
    $l1.Text = 'Starting force:'
    $l1.Location = New-Object System.Drawing.Point(12, 25); $l1.AutoSize = $true
    $tInit = New-Object System.Windows.Forms.TextBox
    $tInit.Location = New-Object System.Drawing.Point(110, 22); $tInit.Width = 625

    $l2 = New-Object System.Windows.Forms.Label
    $l2.Text = 'Wave:'
    $l2.Location = New-Object System.Drawing.Point(12, 55); $l2.AutoSize = $true
    $tWave = New-Object System.Windows.Forms.TextBox
    $tWave.Location = New-Object System.Drawing.Point(110, 52); $tWave.Width = 445

    $l3 = New-Object System.Windows.Forms.Label
    $l3.Text = 'every (sec):'
    $l3.Location = New-Object System.Drawing.Point(565, 55); $l3.AutoSize = $true
    $nInt = New-Object System.Windows.Forms.NumericUpDown
    $nInt.Location = New-Object System.Drawing.Point(640, 52); $nInt.Width = 60
    $nInt.Minimum = 0; $nInt.Maximum = 600; $nInt.Value = 0

    $l4 = New-Object System.Windows.Forms.Label
    $l4.Text = 'Bonus wave:'
    $l4.Location = New-Object System.Drawing.Point(12, 85); $l4.AutoSize = $true
    $tAlt = New-Object System.Windows.Forms.TextBox
    $tAlt.Location = New-Object System.Drawing.Point(110, 82); $tAlt.Width = 445

    $l5 = New-Object System.Windows.Forms.Label
    $l5.Text = 'every Nth:'
    $l5.Location = New-Object System.Drawing.Point(565, 85); $l5.AutoSize = $true
    $nAlt = New-Object System.Windows.Forms.NumericUpDown
    $nAlt.Location = New-Object System.Drawing.Point(640, 82); $nAlt.Width = 60
    $nAlt.Minimum = 1; $nAlt.Maximum = 50; $nAlt.Value = 2

    $g.Controls.AddRange(@($l1, $tInit, $l2, $tWave, $l3, $nInt, $l4, $tAlt, $l5, $nAlt))
    return @{ box = $g; initial = $tInit; wave = $tWave; interval = $nInt; waveAlt = $tAlt; altEvery = $nAlt }
}

$p1 = New-PlayerBox 'Player 1 (Host, red, top zone)' 12 $y
$y += 138
$p2 = New-PlayerBox 'Player 2 (Joiner, blue, bottom zone)' 12 $y
$y += 138

# --- launch ---
$btnLaunch = New-Object System.Windows.Forms.Button
$btnLaunch.Text = 'LAUNCH MATCH'
$btnLaunch.Location = New-Object System.Drawing.Point(12, $y)
$btnLaunch.Size = New-Object System.Drawing.Size(240, 42)
$btnLaunch.Font = New-Object System.Drawing.Font('Segoe UI', 12, [System.Drawing.FontStyle]::Bold)
$btnLaunch.BackColor = [System.Drawing.Color]::FromArgb(60, 140, 60)
$btnLaunch.ForeColor = [System.Drawing.Color]::White

$btnCloseGame = New-Object System.Windows.Forms.Button
$btnCloseGame.Text = 'Close game'
$btnCloseGame.Location = New-Object System.Drawing.Point(265, ($y + 6))
$btnCloseGame.Size = New-Object System.Drawing.Size(110, 30)
$btnCloseGame.Enabled = $false

$tabHost.Controls.AddRange(@($lblPreset, $cmbPreset, $btnSavePreset, $btnDeletePreset, $lblPresetDesc, $grpMatch, $p1.box, $p2.box, $btnLaunch, $btnCloseGame))

# ======================================================== JOIN TAB ==========
$lblJoinInfo = New-Object System.Windows.Forms.Label
$lblJoinInfo.Location = New-Object System.Drawing.Point(15, 15)
$lblJoinInfo.Size = New-Object System.Drawing.Size(740, 55)
$lblJoinInfo.Text = "The host picks the mode and armies. You only need three things:`n1) Be on the same Tailscale network.  2) Sync mod files after the host changes them.  3) Join."

$lblHostIP = New-Object System.Windows.Forms.Label
$lblHostIP.Text = "Host's Tailscale IP:"
$lblHostIP.Location = New-Object System.Drawing.Point(15, 85)
$lblHostIP.AutoSize = $true

$txtHostIP = New-Object System.Windows.Forms.TextBox
$txtHostIP.Location = New-Object System.Drawing.Point(145, 82)
$txtHostIP.Width = 160
$txtHostIP.Text = $script:Config.hostIP

$btnSync = New-Object System.Windows.Forms.Button
$btnSync.Text = 'Sync mod files from GitHub'
$btnSync.Location = New-Object System.Drawing.Point(15, 130)
$btnSync.Size = New-Object System.Drawing.Size(240, 38)

$btnJoin = New-Object System.Windows.Forms.Button
$btnJoin.Text = 'JOIN MATCH'
$btnJoin.Location = New-Object System.Drawing.Point(15, 185)
$btnJoin.Size = New-Object System.Drawing.Size(240, 42)
$btnJoin.Font = New-Object System.Drawing.Font('Segoe UI', 12, [System.Drawing.FontStyle]::Bold)
$btnJoin.BackColor = [System.Drawing.Color]::FromArgb(50, 90, 170)
$btnJoin.ForeColor = [System.Drawing.Color]::White

$btnCloseGame2 = New-Object System.Windows.Forms.Button
$btnCloseGame2.Text = 'Close game'
$btnCloseGame2.Location = New-Object System.Drawing.Point(270, 191)
$btnCloseGame2.Size = New-Object System.Drawing.Size(110, 30)
$btnCloseGame2.Enabled = $false

$txtSyncLog = New-Object System.Windows.Forms.TextBox
$txtSyncLog.Location = New-Object System.Drawing.Point(15, 250)
$txtSyncLog.Size = New-Object System.Drawing.Size(740, 280)
$txtSyncLog.Multiline = $true
$txtSyncLog.ReadOnly = $true
$txtSyncLog.ScrollBars = 'Vertical'
$txtSyncLog.Font = New-Object System.Drawing.Font('Consolas', 9)

$tabJoin.Controls.AddRange(@($lblJoinInfo, $lblHostIP, $txtHostIP, $btnSync, $btnJoin, $btnCloseGame2, $txtSyncLog))

# ----------------------------------------------------------- UI <-> data ----
function Get-UiSettings {
    $attackerSlot = $cmbAttacker.SelectedIndex   # 0 = both, 1 = p1, 2 = p2
    return @{
        map          = $txtMap.Text.Trim()
        roundTimeMin = [int]$numTime.Value
        unitsPerRound = [int]$numMult.Value
        touchdown    = $chkTouchdown.Checked
        wipeoutOnly  = $chkWipeout.Checked
        winScore     = [int]$numScore.Value
        attackerSlot = $attackerSlot
        hostName     = $(if ($script:Config.role -eq 'Host') { $txtMyName.Text.Trim() } else { $txtOppName.Text.Trim() })
        joinName     = $(if ($script:Config.role -eq 'Host') { $txtOppName.Text.Trim() } else { $txtMyName.Text.Trim() })
        players      = @(
            @{ initial = $p1.initial.Text.Trim(); wave = $p1.wave.Text.Trim(); interval = [int]$p1.interval.Value; waveAlt = $p1.waveAlt.Text.Trim(); altEvery = [int]$p1.altEvery.Value },
            @{ initial = $p2.initial.Text.Trim(); wave = $p2.wave.Text.Trim(); interval = [int]$p2.interval.Value; waveAlt = $p2.waveAlt.Text.Trim(); altEvery = [int]$p2.altEvery.Value }
        )
    }
}

function Set-UiFromPreset($pr) {
    if ($pr.map)                       { $txtMap.Text = $pr.map }
    if ($null -ne $pr.roundTimeMin)    { $numTime.Value = [math]::Max($numTime.Minimum, [math]::Min($numTime.Maximum, [int]$pr.roundTimeMin)) }
    if ($null -ne $pr.unitsPerRound)   { $numMult.Value = [math]::Max(1, [int]$pr.unitsPerRound) }
    $chkTouchdown.Checked = [bool]$pr.touchdown
    $chkWipeout.Checked   = [bool]$pr.wipeoutOnly
    if ($null -ne $pr.winScore)        { $numScore.Value = [math]::Max($numScore.Minimum, [math]::Min($numScore.Maximum, [int]$pr.winScore)) }
    if ($null -ne $pr.attackerSlot)    { $cmbAttacker.SelectedIndex = [math]::Max(0, [math]::Min(2, [int]$pr.attackerSlot)) }
    $boxes = @($p1, $p2)
    for ($i = 0; $i -lt 2; $i++) {
        $pl = $pr.players[$i]
        $b = $boxes[$i]
        $b.initial.Text = "$($pl.initial)"
        $b.wave.Text    = "$($pl.wave)"
        $b.waveAlt.Text = "$($pl.waveAlt)"
        $iv = 0; if ($null -ne $pl.interval) { $iv = [int]$pl.interval }
        $ae = 2; if ($null -ne $pl.altEvery -and [int]$pl.altEvery -ge 1) { $ae = [int]$pl.altEvery }
        $b.interval.Value = [math]::Max(0, [math]::Min(600, $iv))
        $b.altEvery.Value = [math]::Min(50, $ae)
    }
    $lblPresetDesc.Text = "$($pr.description)"
}

function Refresh-Presets {
    $script:Presets = @(Get-Presets)
    $cmbPreset.Items.Clear()
    foreach ($pr in $script:Presets) { [void]$cmbPreset.Items.Add($pr.name) }
}

$cmbPreset.Add_SelectedIndexChanged({
    $i = $cmbPreset.SelectedIndex
    if ($i -ge 0 -and $i -lt $script:Presets.Count) { Set-UiFromPreset $script:Presets[$i] }
})

$btnSavePreset.Add_Click({
    $name = [Microsoft.VisualBasic.Interaction]::InputBox('Preset name:', 'Save preset', "$($cmbPreset.Text)")
    if (-not $name) { return }
    $desc = [Microsoft.VisualBasic.Interaction]::InputBox('Short description (optional):', 'Save preset', '')
    $s = Get-UiSettings
    $obj = [ordered]@{
        name = $name; description = $desc
        map = $s.map; roundTimeMin = $s.roundTimeMin; unitsPerRound = $s.unitsPerRound
        touchdown = $s.touchdown; wipeoutOnly = $s.wipeoutOnly
        winScore = $s.winScore; attackerSlot = $s.attackerSlot
        players = $s.players
    }
    $safe = ($name -replace '[^\w\- ]', '') -replace ' +', '-'
    $obj | ConvertTo-Json -Depth 5 | Set-Content -Path (Join-Path $PresetDir "$safe.json") -Encoding utf8
    Refresh-Presets
    $cmbPreset.SelectedIndex = [array]::IndexOf(@($script:Presets | ForEach-Object { $_.name }), $name)
    $lblStatus.Text = "Preset saved: $name"
})

$btnDeletePreset.Add_Click({
    $i = $cmbPreset.SelectedIndex
    if ($i -lt 0) { return }
    $name = $script:Presets[$i].name
    $r = [System.Windows.Forms.MessageBox]::Show("Delete preset '$name'?", 'Delete preset', 'YesNo')
    if ($r -ne 'Yes') { return }
    $safe = ($name -replace '[^\w\- ]', '') -replace ' +', '-'
    $f = Join-Path $PresetDir "$safe.json"
    if (Test-Path $f) { Remove-Item $f -Confirm:$false }
    Refresh-Presets
    $lblStatus.Text = "Preset deleted: $name"
})

# ------------------------------------------------------------- launching ----
$timer = New-Object System.Windows.Forms.Timer
$timer.Interval = 1500
$timer.Add_Tick({
    if ($script:GameProc -and $script:GameProc.HasExited) {
        $script:GameProc = $null
        $timer.Stop()
        $btnLaunch.Enabled = $true
        $btnJoin.Enabled = $true
        $btnCloseGame.Enabled = $false
        $btnCloseGame2.Enabled = $false
        $lblStatus.Text = 'Match ended. Back in the lobby. Adjust settings and launch again when ready.'
        $form.Activate()
    }
})

function Sync-ConfigFromUi {
    $script:Config.role = "$($cmbRole.SelectedItem)"
    $script:Config.myName = $txtMyName.Text.Trim()
    $script:Config.opponentName = $txtOppName.Text.Trim()
    $script:Config.hostIP = $txtHostIP.Text.Trim()
    Save-Config
}

$btnLaunch.Add_Click({
    Sync-ConfigFromUi
    $s = Get-UiSettings
    if (-not $s.map) { [System.Windows.Forms.MessageBox]::Show('Map name is empty.', 'Micro Wars Lobby') | Out-Null; return }
    $scriptPath = Join-Path $GenDir 'host_script.txt'
    New-HostScript $s | Set-Content -Path $scriptPath -Encoding ascii
    if (Start-Game $scriptPath $lblStatus) {
        $btnLaunch.Enabled = $false
        $btnCloseGame.Enabled = $true
        $timer.Start()
    }
})

$btnJoin.Add_Click({
    Sync-ConfigFromUi
    if (-not $script:Config.hostIP) { [System.Windows.Forms.MessageBox]::Show('Enter the host IP first.', 'Micro Wars Lobby') | Out-Null; return }
    $scriptPath = Join-Path $GenDir 'join_script.txt'
    New-JoinScript | Set-Content -Path $scriptPath -Encoding ascii
    if (Start-Game $scriptPath $lblStatus) {
        $btnJoin.Enabled = $false
        $btnCloseGame2.Enabled = $true
        $timer.Start()
    }
})

$closeGame = {
    if ($script:GameProc -and -not $script:GameProc.HasExited) {
        Stop-Process -Id $script:GameProc.Id -Force -Confirm:$false
    }
}
$btnCloseGame.Add_Click($closeGame)
$btnCloseGame2.Add_Click($closeGame)

# ----------------------------------------------------------------- sync -----
$SyncFiles = @(
    @{ url = 'https://raw.githubusercontent.com/Michael-Andrzejewski/Beyond-All-Reason/micro-wars-files/luarules/gadgets/game_micro_wars.lua'; rel = 'luarules\gadgets\game_micro_wars.lua' },
    @{ url = 'https://raw.githubusercontent.com/Michael-Andrzejewski/Beyond-All-Reason/micro-wars-files/modoptions.lua'; rel = 'modoptions.lua' },
    @{ url = 'https://raw.githubusercontent.com/Michael-Andrzejewski/Beyond-All-Reason/micro-wars-files/gamedata/unitdefs.lua'; rel = 'gamedata\unitdefs.lua' }
)

$btnSync.Add_Click({
    Sync-ConfigFromUi
    $sdd = Join-Path $script:Config.dataDir 'games\MicroWars.sdd'
    if (-not (Test-Path $sdd)) {
        $txtSyncLog.AppendText("ERROR: MicroWars.sdd not found at $sdd`r`nInstall the game first (see the setup guide).`r`n")
        return
    }
    $txtSyncLog.AppendText("Syncing mod files into $sdd ...`r`n")
    $ok = $true
    foreach ($f in $SyncFiles) {
        $dest = Join-Path $sdd $f.rel
        try {
            $tmp = "$dest.tmp"
            & curl.exe -sSfL -o $tmp $f.url
            if ($LASTEXITCODE -ne 0) { throw "curl exit $LASTEXITCODE" }
            Move-Item -Force $tmp $dest
            $txtSyncLog.AppendText("  OK  $($f.rel)`r`n")
        } catch {
            $ok = $false
            $txtSyncLog.AppendText("  FAIL $($f.rel): $_`r`n")
        }
    }
    if ($ok) {
        (Get-Item $sdd).LastWriteTime = Get-Date   # bust the engine's checksum cache
        $txtSyncLog.AppendText("Done. Checksum cache refreshed. You are ready to join.`r`n")
        $lblStatus.Text = 'Mod files synced.'
    } else {
        $txtSyncLog.AppendText("Sync had errors. Check your internet connection and try again.`r`n")
    }
})

# --------------------------------------------------------------- startup ----
Add-Type -AssemblyName Microsoft.VisualBasic

$cmbRole.Add_SelectedIndexChanged({
    $isHost = ("$($cmbRole.SelectedItem)" -eq 'Host')
    $tabs.SelectedTab = $(if ($isHost) { $tabHost } else { $tabJoin })
    if ($txtMyName.Text -in @('Michael', 'Mark')) {
        $txtMyName.Text = $(if ($isHost) { 'Michael' } else { 'Mark' })
        $txtOppName.Text = $(if ($isHost) { 'Mark' } else { 'Michael' })
    }
})

$form.Controls.AddRange(@($lblRole, $cmbRole, $lblMyName, $txtMyName, $lblOppName, $txtOppName, $btnUnitNames, $tabs, $lblStatus))

Refresh-Presets
if ($cmbPreset.Items.Count -gt 0) { $cmbPreset.SelectedIndex = 0 }
$tabs.SelectedTab = $(if ($script:Config.role -eq 'Joiner') { $tabJoin } else { $tabHost })

$form.Add_FormClosing({ Sync-ConfigFromUi })

if ($SelfTest) {
    for ($i = 0; $i -lt $script:Presets.Count; $i++) {
        $cmbPreset.SelectedIndex = $i
        $s = Get-UiSettings
        New-HostScript $s | Set-Content -Path (Join-Path $GenDir "selftest_host_$i.txt") -Encoding ascii
        Write-Host "SELFTEST preset $i ($($script:Presets[$i].name)) OK"
    }
    New-JoinScript | Set-Content -Path (Join-Path $GenDir 'selftest_join.txt') -Encoding ascii
    Write-Host 'SELFTEST join OK'
    return
}

[void]$form.ShowDialog()
